export const WALLET_CONNECT_REQUEST = 'WALLET_CONNECT_REQUEST';
export const WALLET_CONNECT_SUCCESS = 'WALLET_CONNECT_SUCCESS';
export const WALLET_CONNECT_FAIL = 'WALLET_CONNECT_FAIL';
export const WALLET_CONNECT_RESET = 'WALLET_CONNECT_RESET';

export const DEPLOY_MY_STORE_REQUEST = 'DEPLOY_MY_STORE_REQUEST';
export const DEPLOY_MY_STORE_SUCCESS = 'DEPLOY_MY_STORE_SUCCESS';
export const DEPLOY_MY_STORE_FAIL = 'DEPLOY_MY_STORE_FAIL';
export const DEPLOY_MY_STORE_RESET = 'DEPLOY_MY_STORE_RESET';

export const SIGN_MY_ITEM_REQUEST = 'SIGN_MY_ITEM_REQUEST';
export const SIGN_MY_ITEM_SUCCESS = 'SIGN_MY_ITEM_SUCCESS';
export const SIGN_MY_ITEM_FAIL = 'SIGN_MY_ITEM_FAIL';
export const SIGN_MY_ITEM_RESET = 'SIGN_MY_ITEM_RESET';

export const BUYER_MINT_AND_REDEEM_REQUEST = 'BUYER_MINT_AND_REDEEM_REQUEST';
export const BUYER_MINT_AND_REDEEM_SUCCESS = 'BUYER_MINT_AND_REDEEM_SUCCESS';
export const BUYER_MINT_AND_REDEEM_FAIL = 'BUYER_MINT_AND_REDEEM_FAIL';
export const BUYER_MINT_AND_REDEEM_RESET = 'BUYER_MINT_AND_REDEEM_RESET';
